### ISSUE TITLE
Didn't work on Windows

### ISSUE THREAD

**Issue by unixfox** [goto-bus-stop/dizzay#2]
When I launch dizzay, the terminal return an error : 

> events.js:72
>         throw er; // Unhandled 'error' event
>               ^
> Error: spawn ENOENT
>     at errnoException (child_process.js:1001:11)
>     at Process.ChildProcess._handle.onexit (child_process.js:792:34)

**Comment by goto-bus-stop** [comment]
Do you have both VLC and youtube-dl installed and in your $PATH? I don't have a Windows installation handy unfortunately, so I can't investigate properly right now ):

**Comment by unixfox** [comment]
Yes I have : 
![](http://u.unixfox.eu/pq9sa)
But not for VLC, how to add vlc to the $PATH ?

**Comment by Sceat** [comment]
With 'vlc' and 'youtube-dl' in the PATH it work but only with mplayer ! not with vlc-player , got this stack

![](http://i.imgur.com/bJuyaRV.png)

**Comment by Sceat** [comment]
@goto-bus-stop Can you add the possibility to launch mplayer with args ?
To stream from Plug.dj to teamspeak in background on windows7 i had to add virtual audio device (with [Virtual Audio Cable](https://virtual-audio-cable.fr.uptodown.com/windows)), that give multiple output
![](http://i.imgur.com/KLgJIVf.png)
so i need to tell mplayer to stream with an other device ! i finally found the how to : `-ao {driver}:device={index}`, i think i can use the mplayer config to specify that but its annoying to specify instead a device each time i want to use mplayer without streaming it to teamspeak :weary: 
i don't even khnow JS but changing this line :

``` js
let instance = spawn('mplayer', [ '-' ], { stdio: [ 'pipe', 'ignore', 'ignore' ] })
```

to

``` js
let instance = spawn('mplayer', [ '-ao','dsound:device=6','-' ], { stdio: [ 'pipe', 'ignore', 'ignore' ] })
```

works for me ! ~~(yup obvious mlg lmao noscope cause it seem to be the way to specify args with a spawn in js :grin: :hear_no_evil: )~~

**Comment by goto-bus-stop** [comment]
44ad36f8d9be091842e6082441408fa68afde561 should've fixed the `spawn ENOENT` issue for VLC. Not sure about @Sceat's VLC issue yet, but I'll be able to test on Windows myself in a bit

**Comment by goto-bus-stop** [comment]
@Sceat Sending plug.dj music to Teamspeak is a really cool idea! As of bf56863fd589399471ad294d3e367acdec84f3c6 it's now possible to pass arguments to mplayer like so:

``` bash
dizzay -r edtentertainment --modules mplayer --mplayer-args "-ao dsound:device=6"
```

Thanks for the suggestion! If there's a problem with the `--mplayer-args` thing, please open a separate issue :)

**Comment by Sceat** [comment]
Nice, thanks ! :smiley: , Concernning the second VLC issue i got this after spawning VLC, vlc instance show up for approximately 2seconds and then crash
